name: CI to Docker Hub
on:
  push:
  pull_request:
jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: "github.ref == 'refs/heads/main'"
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build
        run: ./build.sh aarch64
      - name: Deploy
        if: "github.ref == 'refs/heads/main'"
        run: ./deploy.sh aarch64
  i686:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: "github.ref == 'refs/heads/main'"
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build
        run: ./build.sh i686
      - name: Deploy
        if: "github.ref == 'refs/heads/main'"
        run: ./deploy.sh i686
  x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: "github.ref == 'refs/heads/main'"
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build
        run: ./build.sh x86_64
      - name: Deploy
        if: "github.ref == 'refs/heads/main'"
        run: ./deploy.sh x86_64
  multi_arch:
    needs: [aarch64, i686, x86_64]
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build
        run: docker manifest create griff/nix griff/nix:amd64 griff/nix:i386 griff/nix:arm64v8
      - name: Test
        run: docker build -f Dockerfile.test .
      - name: Deploy
        run: docker manifest push -p griff/nix
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          short-description: The Nix package manager
          repository: griff/nix
