name: CI to Docker Hub
on:
  push:
  pull_request:
jobs:
  aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: "github.ref == 'refs/heads/main'"
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run:
          - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          - ./build.sh aarch64
      - name: Deploy
        if: "github.ref == 'refs/heads/main'"
        run: ./deploy.sh aarch64
