name: "Update Nix version"
on:
  schedule:
    - cron:  '0 12 * * 4'
  repository_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Checkout via SSH
      run: git clone git@github.com:griff/docker-nix.git .
    - run: ./update-version.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: schedule/update-vars
        branch-suffix: timestamp
        commit-message: '[update-version] automated change'
        title: Automatic update
